var sj = [
    {
        name: "校长",
        age: 50,
        number: "111",
        sex: "男",
        zhuanye: "",
        dy: "是",
        city: "成都",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'boos',
    },
    {
        name: "副校长",
        age: 48,
        number: "112",
        sex: "女",
        zhuanye: "",
        dy: "是",
        city: "成都",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'boos1',
    }
]

var teacher = [
    {
        name: "班主任",
        age: 29,
        number: "113",
        sex: "男",
        zhuanye: "",
        bj: 1,
        city: "成都",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'bzr',
    },
    {
        name: "班主任助手",
        age: 25,
        number: "114",
        sex: "女",
        zhuanye: "",
        bj: 2,
        city: "梁山",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'burzs',
    },
    {
        name: "隔壁班主任",
        age: 28,
        number: "115",
        sex: "女",
        zhuanye: "",
        bj: 3,
        city: "攀枝花",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'gbbzr',
    }
]

var student = [
    // 1班
    {
        name: "茂茂",
        age: 18,
        number: "11001",
        sex: "男",
        zhuanye: "前端",
        bj: 1,
        chengji: 98,
        city: "成都",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'mm',
    },
    {
        name: "刘茂",
        age: 18,
        number: "11002",
        sex: "男",
        zhuanye: "前端",
        bj: 1,
        chengji: 87,
        city: "成都",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'lm',
    },
    {
        name: "向雯",
        age: 17,
        number: "11003",
        sex: "女",
        zhuanye: "设计",
        bj: 1,
        chengji: 89,
        city: "内江",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'xw',
    },
    {
        name: "沈周",
        age: 18,
        number: "11004",
        sex: "男",
        zhuanye: "设计",
        bj: 1,
        chengji: 92,
        city: "杭州",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'sz',
    },
    {
        name: "姜贞羽",
        age: 20,
        number: "11005",
        sex: "女",
        zhuanye: "舞蹈",
        bj: 1,
        chengji: 97,
        city: "北京",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'jzy'
    },
    {
        name: "费渡",
        age: 18,
        number: "11006",
        sex: "男",
        zhuanye: "刑侦",
        bj: 1,
        chengji: 99,
        city: "丽江",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'fd',
    },
    // 2班
    {
        name: "雯雯",
        age: 17,
        number: "12001",
        sex: "女",
        zhuanye: "设计",
        bj: 2,
        chengji: 75,
        city: "内江",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'ww',
    },
    {
        name: "叶乾",
        age: 16,
        number: "12002",
        sex: "男",
        zhuanye: "ui",
        bj: 2,
        chengji: 91,
        city: "华阳",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'ww',
    },
    {
        name: "叶烦",
        age: 16,
        number: "12003",
        sex: "男",
        zhuanye: "ui",
        bj: 2,
        chengji: 60,
        city: "华阳",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'yf',
    },
    {
        name: "叶修",
        age: 18,
        number: "12004",
        sex: "男",
        zhuanye: "ui",
        bj: 2,
        chengji: 89,
        city: "安徽",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'yx',
    },
    {
        name: "古力",
        age: 17,
        number: "12005",
        sex: "女",
        zhuanye: "设计",
        bj: 2,
        chengji: 75,
        city: "新疆",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'gl',
    },
    {
        name: "江厌离",
        age: 16,
        number: "12006",
        sex: "女",
        zhuanye: "舞蹈",
        bj: 2,
        chengji: 83,
        city: "莲花坞",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'jyl',
    },
    {
        name: "裴元",
        age: 16,
        number: "12007",
        sex: "男",
        zhuanye: "前端",
        bj: 2,
        chengji: 65,
        city: "黑龙江",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'py',
    },
    // 3班
    {
        name: "节操",
        age: 15,
        number: "13001",
        sex: "男",
        zhuanye: "后端",
        bj: 3,
        chengji: 71,
        city: "巴中",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'jc',
    },
    {
        name: "候节操",
        age: 15,
        number: "13002",
        sex: "男",
        zhuanye: "后端",
        bj: 3,
        chengji: 88,
        city: "巴中",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'hjc',
    },
    {
        name: "伏成",
        age: 14,
        number: "13003",
        sex: "男",
        zhuanye: "前端",
        bj: 3,
        chengji: 93,
        city: "巴中",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'fc',
    },
    {
        name: "伏二代",
        age: 14,
        number: "13004",
        sex: "男",
        zhuanye: "前端",
        bj: 3,
        chengji: 79,
        city: "巴中",
        tp: "学生管理系统\微信图片_20200805100056.png",
        yhm:'fed',
    }
]


